In [9]:
import csv
from PIL import Image
import numpy as np
import os

In [10]:
# Load the image using Pillow
image = Image.open("noisy.png")

# Convert the image to a NumPy array
data = np.array(image)

# Print the shape of the array
print("Array shape:", data.shape)
dim = data.shape
print(data)

Array shape: (551, 414, 3)
[[[207 205 193]
  [203 201 189]
  [170 168 156]
  ...
  [159 159 159]
  [228 227 232]
  [227 226 231]]

 [[201 199 187]
  [197 195 183]
  [211 209 197]
  ...
  [162 162 162]
  [228 227 232]
  [227 226 231]]

 [[191 189 177]
  [209 207 195]
  [204 202 190]
  ...
  [171 171 171]
  [230 229 234]
  [227 226 231]]

 ...

 [[ 38  43  47]
  [ 38  43  47]
  [ 31  36  40]
  ...
  [ 31  34  39]
  [226 229 234]
  [224 227 232]]

 [[ 18  23  27]
  [ 33  38  42]
  [ 27  32  36]
  ...
  [ 29  32  37]
  [226 229 234]
  [226 229 234]]

 [[ 31  36  40]
  [ 53  58  62]
  [ 36  41  45]
  ...
  [ 34  37  42]
  [227 230 235]
  [224 227 232]]]


In [11]:
newdata=data
newdata.shape

(551, 414, 3)

In [12]:
# newdata[1,0,0]=70
newdata

array([[[207, 205, 193],
        [203, 201, 189],
        [170, 168, 156],
        ...,
        [159, 159, 159],
        [228, 227, 232],
        [227, 226, 231]],

       [[201, 199, 187],
        [197, 195, 183],
        [211, 209, 197],
        ...,
        [162, 162, 162],
        [228, 227, 232],
        [227, 226, 231]],

       [[191, 189, 177],
        [209, 207, 195],
        [204, 202, 190],
        ...,
        [171, 171, 171],
        [230, 229, 234],
        [227, 226, 231]],

       ...,

       [[ 38,  43,  47],
        [ 38,  43,  47],
        [ 31,  36,  40],
        ...,
        [ 31,  34,  39],
        [226, 229, 234],
        [224, 227, 232]],

       [[ 18,  23,  27],
        [ 33,  38,  42],
        [ 27,  32,  36],
        ...,
        [ 29,  32,  37],
        [226, 229, 234],
        [226, 229, 234]],

       [[ 31,  36,  40],
        [ 53,  58,  62],
        [ 36,  41,  45],
        ...,
        [ 34,  37,  42],
        [227, 230, 235],
        [224, 227, 232]]

In [13]:
nae=[]

In [14]:

for row in data:
    # print(f'{row}\n\n{row[0]}\n\n{row[0,0]}\n\n{row.shape}')
    nae.append(data[0,1,0])
    print(nae)
    break

[203]


In [15]:
#this is fucking slow way                                        551, 414, 3

def writer(data):
    file_name = "encrypted.csv"
    with open(file_name, mode="w", newline="") as csv_file:
        
    # Create a CSV writer object
        writer = csv.writer(csv_file)

    # Write the data to the CSV file
        for x in range(0,551):
            liss=[]
            for y in range(0,414):
                for z in range(0,3):
                    liss.append(data[x,y,z])
            writer.writerow(liss)
    os.system(f'start excel {file_name}')
 
writer(data)
    

sh: start: command not found


In [16]:
finar=[]
with open("encrypted.csv", mode="r") as csv_file:
    num = csv_file.readline(1242)
    
    for ay in range(0,413):
        arr=[]
        for ele in range(0,2):    
            x=num[ele]
            arr.apppend(x)
        finar.append(arr)
print(finar)

AttributeError: 'list' object has no attribute 'apppend'

(551, 414, 3)

In [ ]:

pfinar=[]
index=0
with open("encrypted.csv", mode="r") as csv_file:
    num = csv_file.readline()
    num = num.split(',')
    print(len(num))
    rang= int(len(num)/3)
    
    for rld in range(0,551):
        finar=[]
        for j in range(rang):

            tarr=[]
            while index>1242:
                for i in range(3):
                    print(index)                
                    tarr.append(num[index])
                    index+=1
                finar.append(tarr)
            # for x57 in range(0,3)
        pfinar.append(finar)
    
print(len(finar))

1242
0


In [ ]:
finar=[]

index=0
with open("encrypted.csv", mode="r") as csv_file:
    num = csv_file.readline()
    num = num.split(',')
    print(len(num))
    rang= int(len(num)/3)
    
    for j in range(rang):
        # print(j)
        tarr=[]
        for i in range(3):
            
            tarr.append(num[index])
            index+=1
        finar.append(tarr)
        # for x57 in range(0,3)

    
print(len(finar))

1242
414


In [ ]:

dataaa = []
with open("encrypted.csv", mode="r") as csv_file:
    reader = csv.reader(csv_file)
    rows=list(reader)
    for row in reader:
        # row=np.array(row)
        print(row[0,0])    
    # for i in range(414):
    #     dataaa.append(row[i])
        
        # dataaa.append([int(cell) for cell in row])
# dataaa=np.array(dataaa)
print(dataaa)

[]


In [ ]:
writer(data)
filename = "encrypted.csv"

In [ ]:
new_image = Image.fromarray(newdata)

# Save the new image to a file
new_image.save("new_image.png")